CREATE TYPE move_type AS ENUM ('selection', 'placement');

CREATE TABLE moves (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "gameId" uuid REFERENCES games(id),
  "moveType" move_type NOT NULL,
  value INTEGER NOT NULL
);